<a href="https://colab.research.google.com/github/TatarinovaEM758/Machine_learning/blob/main/ML_3_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Перцептрон

#### Цель работы

Познакомиться с перцептроном как с моделью обучения с учителем в библиотеке sklearn.

#### Содержание работы

1. Сгенерируйте данные и обучите на них модель перцептрона.
1. Просмотрите параметры модели, визуализируйте и улучшите ее работу.

#### Методические указания

Для тренировки работы с перцептроном создадим набор данных. Воспользуемся уже знакомыми функциями генерации данных. Сразу после создания визуализируем этот набор данных на диаграмме рассеяния:

In [ ]:
blob_centers = ([1, 1], [3, 4], [1, 3.3], [3.5, 1.8])
X, y = make_blobs(n_samples=200,
                          centers=blob_centers,
                          cluster_std=0.5,
                          random_state=0)

X[:, 0] *= 1000

plt.scatter(X[:, 0], X[:, 1], c=y,  edgecolors='black',linewidth=1)


NameError: name 'make_blobs' is not defined

Вы должны увидеть набор данных, состоящий из четырех кластеров, принадлежащий четырем классам:



То есть мы имеем дело с задачей множественной классификации. Для перцептрона это не проблема, нейросеть это очень универсальная модель, она может работать нативно и в множественном режиме. Давайте создадим первую версию нашей нейросети:

In [ ]:
clf = MLPClassifier(hidden_layer_sizes=(6,),
                    random_state=1).fit(X, y)

NameError: name 'MLPClassifier' is not defined

Обратите внимание, что при создании мы задаем количество слоев и количество нейронов в каждом из них с помощью кортежа hidden_layer_sizes. В данном случае имеем один скрытый слой в 6 нейронов. Если мы не зададим этот аргумент, то его значение по умолчанию - (100,), то есть один слой со ста нейронами. Этого для первой моедли будет довольно много.

Так как мы уже обучили модель, мы можем посмотреть значения весов нейронов, то есть внутренние параметры нейросети. Все они хранятся в поле coefs_, аналогично другим моделям машинного обучения в sklearn. Например, можно вывести веса отдельно для каждого слоя:

In [ ]:
print("Веса между входным и скрытым слоем:")
print(clf.coefs_[0])
print("\nВеса между скрытым и выходным слоем:")
print(clf.coefs_[1])

Веса между входным и скрытым слоем:


NameError: name 'clf' is not defined

In [ ]:
Веса между входным и скрытым слоем:
[[-0.13186096  0.36276684 -0.87753229 -0.3544923  -0.62342741 -0.69458326]
 [-0.55527141 -0.28633324 -0.1793465   0.07807555 -0.14370807  0.32689274]]

Веса между скрытым и выходным слоем:
[[-0.4955391  -0.41463226  0.41301641  0.65040935 -0.25197168  0.26165608]
 [ 0.5134373   0.53925562 -0.57325313 -0.6379063  -0.4542433   0.51596208]
 [-0.55456344 -0.10522807  0.63360879  0.03543427  0.28300565 -0.25076137]
 [ 0.25356345  0.4604906  -0.66711811  0.3423877   0.70293671  0.33948522]
 [-0.29956981  0.3969661  -0.54770982 -0.0851425   0.58948128 -0.28122352]
 [-0.28935468 -0.51007606 -0.6656005   0.24156416 -0.39625967 -0.3203444 ]]

Либо по каждому нейрону отдельно:

In [ ]:
for i in range(len(clf.coefs_)):
    number_neurons_in_layer = clf.coefs_[i].shape[1]
    for j in range(number_neurons_in_layer):
        weights = clf.coefs_[i][:,j]
        print(i, j, weights, end=", ")
        print()
    print()

NameError: name 'clf' is not defined

In [ ]:
0 0 [-0.09809877 -0.58903611],
0 1 [ 0.33667051 -0.31219238],
0 2 [-0.82024119 -0.22424296],
0 3 [-0.29720839  0.11423652],
0 4 [-0.56852789 -0.18324369],
0 5 [-0.66056109  0.37321781],

1 0 [-0.51316658 -0.24370005 -0.59713359 -0.5769702   0.34285864 -0.7006119 ],
1 1 [-0.43365467  0.34328608 -0.67678056 -0.10221922 -0.25645017  0.35515533],
1 2 [ 0.43189995  0.57835494 -0.46609801  0.75476969  0.33417991  0.80295119],
1 3 [0.68148414 0.57889271 0.54011704 0.00610289 0.47281254 0.33880635],

Обратите внимание, что судя по выведенной информации, на выходном слое у нас четыре нейрона. Это обусловлено тем, что в датасете четыре класса. Количество классов всегда определяет количество нейронов на выходном слое. А на входном слое у нас два нейрона. Это потому, что в датасете всего две атрибута.

Веса нейронов смещения (bias) как и в других моделях хранятся в отдельном поле:

In [ ]:
print("Веса смещения для скрытого слоя:")
print(clf.intercepts_[0])
print("\nВеса смещения для выходного слоя:")
print(clf.intercepts_[1])

In [ ]:
Веса смещения для скрытого слоя:
[-0.55752645  0.60978582 -0.8640854   0.33258994 -0.18652436  0.05696655]

Веса смещения для выходного слоя:
[-0.29413473  0.49414359 -0.60792984 -0.11888525]

Давайте проанализируем, насколько хорошо работает наша модель. Для этого воспользуемся уже знакомой матрицей классификации:

In [ ]:
confusion_matrix(y, clf.predict(X))

In [ ]:
array([[ 1,  0, 49,  0],
       [ 0,  0, 50,  0],
       [ 1,  0, 49,  0],
       [ 0,  0, 50,  0]])

Мы видим, что как будто модель работает не совсем корректно и делает много ошибок. Чтобы убедиться в этом, изобразим классификацию на графике:

In [ ]:
X0 = np.linspace(X[:, 0].min()-1,X[:, 0].max()+1, X.shape[0])
X1 = np.linspace(X[:, 1].min()-1,X[:, 1].max()+1, X.shape[0])
X0_grid, X1_grid = np.meshgrid(X0, X1)

y_predict = clf.predict(np.c_[X0_grid.ravel(),X1_grid.ravel()]).reshape(X0_grid.shape)
plt.pcolormesh(X0_grid, X1_grid, y_predict)

plt.scatter(X[:, 0], X[:, 1], c=y,  edgecolors='black',linewidth=1)
plt.xlabel('X1')
plt.ylabel('X2')
plt.show()

На примере данного кода познакомьтесь со способом изображения границы принятия решений для множественной классификации. Мы видим довольно странную картину:


Почти все точки модель относит к одному классу. А граница принятия решений почти всегда вертикальна. Что мы сделали не так? Для ответа на этот вопрос надо обратить внимание на подпись осей координат. Дело в том, что атрибуты в исходных данных имеют очень разные значения.
X
1
 измеряется в тысячах, а
X
2
 - в единицах. Это может стать проблемой для неекоторых моделей машинного обучения. И перцептрон - одна из них. Для корректной работы перцептрона данные нужно обязательно нормализовать.

Для этого импортируем и воспользуемся объектом нормализации данных. Наример, таким:

In [ ]:
from sklearn.preprocessing import StandardScaler
X_scaled = scaler.transform(X)
X_scaled = scaler.transform(X)

Давайте еще раз изобразим точки на графике, чтобы понять, как нормализация преобразовала наш датасет:



Само распределение как будто не изменилось, но обратите внимание на значения по осям. Теперь наш датасет имеет одинаковую размерность. Данные как будто "ужались" по горизонтали. Давайте посмотрим, повлияет ли это на качество обучения. Переобучим модель и выведем матрицу классификации:

In [ ]:
array([[22,  0, 11, 17],
       [ 0, 38,  0, 12],
       [ 0,  3, 45,  2],
       [ 0,  5,  0, 45]])

Мы видим совершенно другую картину. Стало значительно лучше. Для большей уверенности изобразим классификацию на графике:



Мы видим, что регионы сооветствующих классов уже гораздо ближе к точкам обучающей выборки. При этом модель все еще делает довольно много ошибок. Как можно просто ее улучшить? вы могли обратить внимание, что при обучении модель выдавал предупреждение о раннем прерывании обучения. Мы уже сталкивались с такой ситуацией. Можно просто увеличить лимит итераций алгоритма обучения:

In [ ]:
clf = MLPClassifier(hidden_layer_sizes=(6,), max_iter=10_000, verbose=True).fit(X_scaled, y)

Заодно здесь мы применим еще один аргумент конструктора объекта перцептрона - verbose. Он позволяет вывести подробную информацию про обучение модели. Проанализируйте полученную информацию и сделайте вывод.

Теперь можно вывести матрицу классификации. Сразу видно, что опять стало значительно лучше:

In [ ]:
array([[50,  0,  0,  0],
       [ 0, 50,  0,  0],
       [ 2,  3, 45,  0],
       [ 0,  1,  0, 49]])

Этот вывод подтверждает и визуализация модели:



Для дальнейшего повышения точности можно увеличить количество скрытых слоев. Тогда получится уже глубокая нейросеть. Например, обучим перцептрон с тремя слоями:

In [ ]:
clf = MLPClassifier(hidden_layer_sizes=(6, 6, 6), max_iter=10_000).fit(X_scaled, y)

Из графика видно, что граница принятия решений еще больше соответствует обучающей выборке. Постройте матрицу классификации этой модели самостоятельно.




Задания для самостоятельного выполнения
1. Создайте однослойный перцептрон с 1, 2, 10 и 100 нейронами. Сравние их точность
и сделайте вывод о достаточном количестве нейронов.
2. Создайте и оцените модель с двумя, тремя и десятью скрытыми слоями с одинаковым количеством нейронов. Сравните их точность и сделайте вывод о достаточном количестве слоев.
3. Для глубокой модели выведите веса всех нейронов на всех слоях. Выведите значения векторов весов смещения.
4. Постройте и оцените модель с большим количеством нейронов и слоев. Замерьте время выполнения обучения, сравните со временем обучения более простых моделей.
5. Постройте и оцените модель классификации с помощью перцептрона на датасете, который вы использовали на контрольной по классификиации (если вы ее не выполняли, возьмите любой датасет из раздела "real world datasets" в библиотеке sklearn).
6. Постройте и оцените модель регрессии с помощью перцептрона на датасете, который вы использовали на контрольной по регрессии.

### 1. Создайте однослойный перцептрон с 1, 2, 10 и 100 нейронами. Сравние их точность и сделайте вывод о достаточном количестве нейронов.

In [ ]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

# Загружаем данные Iris
data = load_iris()
X = data.data
y = data.target

# Разделяем данные на обучающую и тестовую выборки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Списки для хранения результатов
results = []

# Определяем количество нейронов
neurons = [1, 2, 10, 100]

for n in neurons:
    # Создаем однослойный перцептрон
    model = MLPClassifier(hidden_layer_sizes=(n,), max_iter=1000, random_state=42)

    # Обучаем модель
    model.fit(X_train, y_train)

    # Предсказываем на тестовой выборке
    y_pred = model.predict(X_test)

    # Вычисляем точность
    accuracy = accuracy_score(y_test, y_pred)
    results.append((n, accuracy))

# Печатаем результаты
for n, acc in results:
    print(f"Количество нейронов: {n}, Точность: {acc:.4f}")

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


Количество нейронов: 1, Точность: 0.8667
Количество нейронов: 2, Точность: 0.8667
Количество нейронов: 10, Точность: 0.9667
Количество нейронов: 100, Точность: 1.0000


1. Низкое количество нейронов (1-2): Перцептрон с одним или двумя нейронами может показать неплохие результаты на простых задачах, но, как правило, его точность недостаточно высока для более сложных задач.

2. Умеренное количество нейронов (10): Увеличение числа нейронов улучшает способность модели к обучению, что обычно приводит к повышению точности.

3. Слишком большое количество нейронов (100): Здесь наблюдается потенциальная проблема переобучения, особенно если данных недостаточно. Однако на простых, хорошо разделяемых данных, таких как Iris, точность может оставаться высокой.

### 2. Создайте и оцените модель с двумя, тремя и десятью скрытыми слоями с одинаковым количеством нейронов. Сравните их точность и сделайте вывод о достаточном количестве слоев.

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

# Загрузка данных
data = load_iris()
X = data.data
y = data.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Функция для создания модели
def create_model(num_layers):
    model = keras.Sequential()
    model.add(keras.layers.InputLayer(input_shape=(X.shape[1],)))
    for _ in range(num_layers):
        model.add(keras.layers.Dense(64, activation='relu'))
    model.add(keras.layers.Dense(3, activation='softmax'))  # 3 класса для Iris
    return model

# Обучение и оценка моделей
results = {}
for num_layers in [2, 3, 10]:
    model = create_model(num_layers)
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    model.fit(X_train, y_train, epochs=100, verbose=0)
    test_loss, test_accuracy = model.evaluate(X_test, y_test, verbose=0)
    results[num_layers] = test_accuracy

# Вывод результатов
print("Точности моделей с различным количеством слоев:")
for num_layers, accuracy in results.items():
    print(f"Скрытых слоев: -> Точность: {accuracy:.4f}")



/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Точности моделей с различным количеством слоев:
Скрытых слоев: -> Точность: 0.9667
Скрытых слоев: -> Точность: 0.9667
Скрытых слоев: -> Точность: 0.9667


При анализе точности моделей можно сделать следующие выводы:

1. **Слишком мало слоев**: Если количество слоев слишком маленькое (например, 2), модель может быть недостаточно мощной для захвата сложных зависимостей в данных.

2. **Оптимальное количество слоев**: При увеличении числа слоев (например, до 3 или 4) может наблюдаться повышение точности, если данные достаточно сложные.

3. **Слишком много слоев**: После определенного момента (например, 10 слоев) точность может не увеличиваться или даже снижаться, что может быть связано с переобучением и трудностью в оптимизации более сложной модели.

Таким образом, идеальное количество слоев зависит от конкретных данных и задачи, и оптимальное решение обычно требует экспериментов и кросс-валидации.

### 3. Для глубокой модели выведите веса всех нейронов на всех слоях. Выведите значения векторов весов смещения.

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

# Пример создания простой модели
model = keras.Sequential([
    keras.layers.Dense(64, activation='relu', input_shape=(32,)),  # Входной слой
    keras.layers.Dense(64, activation='relu'),                    # Скрытый слой
    keras.layers.Dense(10, activation='softmax')                  # Выходной слой
])

# Компиляция модели
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Предположим, модель уже обучена

# Получаем веса и смещения для каждого слоя
for layer in model.layers:
    weights, biases = layer.get_weights()  # Получаем веса и смещения
    print(f"Layer: {layer.name}")
    print(f"Weights shape: {weights.shape}")
    print(weights)
    print(f"Biases shape: {biases.shape}")
    print(biases)
    print("-" * 40)  # Разделитель для удобства чтения

Layer: dense_18
Weights shape: (32, 64)
[[ 0.14744031 -0.1288696  -0.2449466  ... -0.14188051  0.16493642
   0.22115642]
 [-0.13016915 -0.06086582 -0.1343059  ...  0.2187028   0.05806601
   0.01879668]
 [-0.23085725  0.05213183 -0.19977772 ... -0.12639946 -0.19202214
   0.06983089]
 ...
 [ 0.07923406 -0.14097947 -0.12072426 ...  0.1784687   0.12230533
   0.16465646]
 [ 0.11793143  0.17105836  0.2079876  ...  0.12940389  0.23902172
  -0.1489793 ]
 [-0.17862481  0.20256758  0.20135349 ... -0.2415781  -0.0029906
  -0.2177077 ]]
Biases shape: (64,)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
----------------------------------------
Layer: dense_19
Weights shape: (64, 64)
[[ 0.1831684   0.17487486  0.01945257 ... -0.13368809 -0.09582891
  -0.00688191]
 [-0.14622751  0.17976184  0.16504769 ...  0.21449561  0.1493945
   0.20397817]
 [ 0.206430

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


### 4. Постройте и оцените модель с большим количеством нейронов и слоев. Замерьте время выполнения обучения, сравните со временем обучения более простых моделей.

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import time

# Загрузка данных MNIST
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()
x_train, x_test = x_train.astype("float32") / 255.0, x_test.astype("float32") / 255.0
x_train = np.expand_dims(x_train, -1)
x_test = np.expand_dims(x_test, -1)

# Простой модель
def build_simple_model():
    model = keras.Sequential([
        layers.Flatten(input_shape=(28, 28, 1)),
        layers.Dense(128, activation='relu'),
        layers.Dense(10, activation='softmax')
    ])
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

# Большая модель
def build_large_model():
    model = keras.Sequential([
        layers.Flatten(input_shape=(28, 28, 1)),
        layers.Dense(512, activation='relu'),
        layers.Dense(512, activation='relu'),
        layers.Dense(512, activation='relu'),
        layers.Dense(10, activation='softmax')
    ])
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

# Обучение простой модели
simple_model = build_simple_model()
start_time = time.time()
simple_model.fit(x_train, y_train, epochs=5, batch_size=32, validation_split=0.2, verbose=0)
simple_time = time.time() - start_time
print(f"Simple model training time: seconds")

# Обучение большой модели
large_model = build_large_model()
start_time = time.time()
large_model.fit(x_train, y_train, epochs=5, batch_size=32, validation_split=0.2, verbose=0)
large_time = time.time() - start_time
print(f"Large model training time: seconds")

# Оценка производительности
simple_loss, simple_acc = simple_model.evaluate(x_test, y_test, verbose=0)
large_loss, large_acc = large_model.evaluate(x_test, y_test, verbose=0)

print(f"Simple model accuracy: {simple_acc:.4f}")
print(f"Large model accuracy: {large_acc:.4f}")

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Simple model training time: seconds
Large model training time: seconds
Simple model accuracy: 0.9767
Large model accuracy: 0.9711


Большая модель будет обучаться значительно дольше по сравнению с простой моделью, а также ее точность может не сильно отличаться от точности простой модели. Это будет показывать, что увеличение количества параметров не всегда приводит к значительному увеличению производительности.

### 5. Постройте и оцените модель классификации с помощью перцептрона на датасете, который вы использовали на контрольной по классификиации (если вы ее не выполняли, возьмите любой датасет из раздела "real world datasets" в библиотеке sklearn).

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Загрузка датасета Iris
iris = load_iris()
X = iris.data
y = iris.target

# Разделение данных на обучающую и тестовую выборки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Стандартизация данных
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Создание и обучение модели перцептрона
perceptron = Perceptron(max_iter=1000, random_state=42)
perceptron.fit(X_train, y_train)

# Предсказания на тестовой выборке
y_pred = perceptron.predict(X_test)

# Оценка модели
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy:.2f}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)

Accuracy: 0.93
Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  2  9]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.82      1.00      0.90         9
           2       1.00      0.82      0.90        11

    accuracy                           0.93        30
   macro avg       0.94      0.94      0.93        30
weighted avg       0.95      0.93      0.93        30



Мы получили значение точности (accuracy), матрицу ошибок (confusion matrix) и отчет о классификации (classification report), который включает такие метрики, как precision, recall и f1-score для каждого класса.

### 6. Постройте и оцените модель регрессии с помощью перцептрона на датасете, который вы использовали на контрольной по регрессии.

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# 1. Загрузка данных
data = pd.read_csv('Linear-regression.csv')

# 2. Предобработка данных (при необходимости)
# Например, удаление или заполнение пропусков
data.fillna(data.mean(), inplace=True)

# 3. Определение признаков и целевой переменной
X = data.drop('Y', axis=1)
y = data['Y']

# 4. Разделение данных на обучающую и тестовую выборки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 5. Создание и обучение модели
model = MLPRegressor(hidden_layer_sizes=(100,), max_iter=1000, random_state=42)
model.fit(X_train, y_train)

# 6. Оценка модели
y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'MAE: {mae}')
print(f'MSE: {mse}')
print(f'R²: {r2}')

MAE: 2.14770129704598
MSE: 4.94337847190673
R²: 0.9985512278661044
